FROM node:22-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY prisma ./prisma
ENV DATABASE_URL="postgresql://postgres:postgres@postgres:5432/medical_appointment?schema=public"
RUN npx prisma generate

EXPOSE 4000

CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npm run dev"]
